language: java
sudo: required
services:
  - docker
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test "$TRAVIS_TAG" != "" && test $TRAVIS_REPO_SLUG == "version-aware/gradle-updater" && ./gradlew dockerPush -Pversion="$TRAVIS_TAG" --info

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
